# Generated by Django 3.2 on 2025-05-23 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Brief description of what this competency entails.')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('categories', models.ManyToManyField(to='assessments.Category')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.competency')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sophistication_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('is_scope_question', models.BooleanField(default=False)),
                ('interpretation_guidance', models.TextField(blank=True, help_text='Guidance on how to interpret the answer.')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.category')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.competency')),
                ('next_if_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_followups', to='assessments.question')),
                ('next_if_yes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yes_followups', to='assessments.question')),
            ],
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField(blank=True, help_text='Summary of what this role usually does.')),
                ('history', models.TextField(blank=True, help_text='Brief history of the role.')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.department')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_category_index', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chosen_scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.scope')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.competency')),
                ('current_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.question')),
                ('selected_competencies', models.ManyToManyField(blank=True, related_name='sessions', to='assessments.Competency')),
            ],
        ),
        migrations.AddField(
            model_name='competency',
            name='gateway_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competency_gateway', to='assessments.question'),
        ),
        migrations.AddField(
            model_name='competency',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.jobtitle'),
        ),
        migrations.AddField(
            model_name='competency',
            name='scope_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competency_scope', to='assessments.question'),
        ),
        migrations.AddField(
            model_name='category',
            name='competency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.competency'),
        ),
        migrations.AddField(
            model_name='category',
            name='starting_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_start', to='assessments.question'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('feedback', models.TextField(blank=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.interviewsession')),
            ],
        ),
    ]
